// This file was generated by a Flutter project generator.
// Do not edit this file manually.
// If you need to modify your project structure, please use the generator script.

import 'dart:io';

Map<String, List<String>> directories = {
  "app": [],
  "data": [],
  "domain": [],
  "presentation": [],
  "app/config": [],
  "app/core": [],
  "app/utils": [],
  "presentation/bloc": [],
  "presentation/controller": [],
  "presentation/pages": [],
  "presentation/widget": [],
  "domain/entities": [],
  "domain/repositories": [],
  "domain/usecases": [],
  "data/models": [],
  "data/datasource": [],
  "data/repositories": [],
  "": ["generator.dart"],
};

Future<Directory?> createDirectory(String path) async {
  try {
    final newDir = Directory(path);
    newDir.createSync(recursive: true);
    return newDir;
  } catch (e) {}
  return null;
}

Future<File?> createFile(String path, String fileName) async {
  try {
    final file = File("/$path/$fileName");
    final f = await file.create();
    return f;
  } catch (e) {}
  return null;
}
