name: dart_clean_generator
version: 1.0.0
description: Dart Generator for Bloc Application
repository: https://github.com/olawills/olawills-dart-generator

environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  ansicolor: ^2.0.2
  args: ^2.4.2
  build: ^2.4.1
  lints: ^3.0.0
dev_dependencies:
  build_runner: ^2.4.6
  source_gen: ^1.4.0
