name: olawills_clean_arch_gen
version: 1.0.0
description: A simple clean architecture generator.
homepage: https://github.com/olawills/olawills-dart-generator

environment:
  sdk: ">=3.0.5 <4.0.0"

executables:
  generator: main.dart
